//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bat.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRecord
    {
        public int ID { get; set; }
        public int Lesson_ID { get; set; }
        public string Chat_User { get; set; }
        public string Char_Message { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
