//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bat.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int ID { get; set; }
        public int Account_ID { get; set; }
        public System.DateTime EventDate { get; set; }
        public string IPAddress { get; set; }
        public string Type { get; set; }
        public string Data { get; set; }
    }
}
