//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bat.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonResource
    {
        public int ID { get; set; }
        public int Lession_ID { get; set; }
        public string Original_Name { get; set; }
        public string Item_Storage_Name { get; set; }
        public Nullable<int> Type_ID { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
