//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bat.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.ChatRecords = new HashSet<ChatRecord>();
            this.LessonAttachments = new HashSet<LessonAttachment>();
            this.LessonParticipants = new HashSet<LessonParticipant>();
            this.LessonResources = new HashSet<LessonResource>();
        }
    
        public int ID { get; set; }
        public int Account_ID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int DurationMins { get; set; }
        public string Description { get; set; }
        public int ClassSize { get; set; }
        public string TokBoxSessionId { get; set; }
        public string ZoomStartUrl { get; set; }
        public string ZoomJoinUrl { get; set; }
        public string Subject { get; set; }
        public string DetailedDescription { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRecord> ChatRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonAttachment> LessonAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonParticipant> LessonParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonResource> LessonResources { get; set; }
    }
}
