//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bat.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonParticipant
    {
        public int ID { get; set; }
        public int Lesson_ID { get; set; }
        public int Account_ID { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
