//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bat.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectExamPaper
    {
        public int ID { get; set; }
        public int SubjectDescription_ID { get; set; }
        public string StorageName { get; set; }
        public string Original_Name { get; set; }
    
        public virtual SubjectDescription SubjectDescription { get; set; }
    }
}
